import React from 'react';

export default [
  {
    id: 1,
    name: 'Cheese',
    price: '$4.90',
    stock: 20,
    day: 'Friday',
    saledaynum: 5,
    url: '',
  },
  {
    id: 2,
    name: 'Milk',
    price: '$1.90',
    stock: 4,
    day: 'Monday',
    saledaynum: 1,
  },
  {
    id: 3,
    name: 'Yoghurt',
    price: '$2.40',
    stock: 12,
    day: 'Thursday',
    saledaynum: 4,
  },
  {
    id: 4,
    name: 'Heavy Cream',
    price: '$3.90',
    stock: 9,
    day: 'Tuesday',
    saledaynum: 2,
  },
  {
    id: 5,
    name: 'Butter',
    price: '$0.90',
    stock: 99,
    day: 'Wednesday',
    saledaynum: 3,
  },
  {
    id: 6,
    name: 'Sour Cream',
    price: '$2.90',
    stock: 86,
    day: 'Saturday',
    saledaynum: 6,
  },
  {
    id: 7,
    name: 'Fancy French Cheese',
    price: '$99.0',
    stock: 15,
    url: <a href='https://google.com'>hello google</a>,
    day: 'Sunday',
    saledaynum: 0,
  },
  { id: 8, name: 'Eggs', price: '$1.90', stock: 86 },
  {
    id: 9,
    name: 'Ricotta Cheese',
    price: '$3.99',
    stock: 6,
    day: 'Saturday',
    saledaynum: 6,
  },
  { id: 10, name: 'Frozen Custard', price: '$5.50', stock: 11 },
  {
    id: 11,
    name: 'Whey Powder',
    price: '$15.90',
    stock: 8,
    day: 'Wednesday',
    saledaynum: 3,
  },
];
