# NOTE: This create a very simple image that has the proper version of Node.
# This image does not contain any project files.
# See docker-container-dev-env.yml file and Readme for how this can be used
# during development.

FROM node:16-buster


# Where inside the container the files will appear
WORKDIR /home/app

# Install SSH config
RUN mkdir -p /root/.ssh 
ADD DOCKER_DEV_ENV/sshConfig /root/.ssh/config


RUN apt-get update
RUN apt-get install vim -y


# Ports
ENV PORT 3000
EXPOSE 3000

# Opens the terminal inside the container
ENTRYPOINT /bin/bash