name: Publish NPM Package
on:
  workflow_run:
    workflows:
      - 'Version and tag'
    types:
      - completed

jobs:
  publish:
    name: publish module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@mydobie'

      - name: Install dependencies
        run: npm run d

      - name: Build package
        run: bash  utils/buildPackage.sh

      - name: Publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build:hash

      - name: Deploy to GH pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
