name: Publish Package
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/

          scope: '@mydobie'

      - name: Install dependencies
        run: npm run d

      - name: Build package
        run: bash  utils/buildPackage.sh

      - name: Publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
