name: Tag NPMBuild
on:
  workflow_dispatch:

jobs:
  commit:
    name: commit module code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          ref: npmbuild
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: npmbuild${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
