name: Test Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm run d

      - name: Tests
        run: npm run test

      - name: Test coverage
        run: npm run checkCoverage

      - name: Linting
        run: npm run lint

      - name: Security audit
        run: npm run npmAudit

      - name: Can module be built
        run: bash  utils/buildPackage.sh
